---
title: "Personas Desaparecidas en México"
subtitle: "Almacenes y Minería de Datos"
date: today
format:
  dashboard:
    theme: sandstone
    nav-buttons: [github]
  html:
    toc: true
    code-fold: true
  pdf:
    toc: true
execute:
  echo: true
  warning: false
jupyter: python3
---

# Empresa y Metodología de Minería de Datos

# Dataset: Personas Desaparecidas en México

Creación del dataframe a partir del csv "tot_reg_desap.csv"
```{python}
import pandas as pd

df = pd.read_csv('tot_reg_desap.csv')
```

## Descripción del dataset

```{python}
df.info()
```

# Medidas Descriptivas y Análisis Exploratorio de Datos (EDA)

## Diccionario de Datos

## CRISP-DM

### Business Understanding
### Data Understanding
### Data Preparation
### Modelling
### Evaluation
### Deployment

## Cálculo de Medidas

### Medidas de localización
### Medidas de variabilidad
### Medidas de heterogeneidad
### Medidas de concentración

# Correlación

# Limpieza del dataset: Documentación

```{python}
df_raw = pd.read_csv(
    "tot_reg_desap.csv",
    index_col=0,
    keep_default_na=False,
    na_values=["NA", "N/A", "", " "],
)
 
df_limpieza = df_raw.copy()
```

## 1. Valores faltantes

Revisamos los datos faltantes por cada columna:

```{python}
nulos = df_limpieza.isnull().sum()
porcentaje = df_limpieza.isnull().mean() * 100

resumen = pd.DataFrame({
    "nulos": nulos,
    "porcentaje": porcentaje.round(2)
})

print(resumen)
```

Encontramos que las siguientes columnas son las que presentan espacios nulos en distintos procentajes: estatus_busqueda, fub, DC_id, fecha_desap.

### Columna *estatus_busqueda*

Un dato faltante en esta columna significa que para una persona desaparecida registrada no se sabe si ya fue localizada, si no se cuenta con ningún indicio de la persona o si está en proceso de búsqueda.

La cantidad de datos faltantes en esta columna representa el 30.5% (27,364 registros), lo que significa que para el 30.5% de las personas registradas como desaparecidas se desconoce el estatus de su búsqueda. Eliminar los registros que no cuentan con este dato significa descartar la información de personas desaparecidas, esto crea un sesgo en el análisis de las cifras porque estaríamos descartando más de 27 mil registros que puede que cuenten con los datos de las otras columnas y nos puede proporcionar información útil respecto al tema.

Para proceder con esta falta de información, en lugar de eliminar las filas con este dato vacío, de decidió rellenar con el nuevo estado "Sin estatus encontrado", con lo que podemos seguir contando con la otra información sin necesidad de eliminarlo y conservamos la información registrada para cada persona.

```{python}
df_limpieza["estatus_busqueda"] = df_limpieza["estatus_busqueda"].fillna("Sin estatus registrado")
```

Ahora consideramos la información completa pero contando con 27,364 registros de personas desaparecidas de las que no se sabe su estatus de búsqueda.

### Columna *fub*

# Hallazgos

# Conclusiones